dataset: 'gaia'
base_path: '.'
demo_path: 'data/gaia/demo'
label: 'demo_1100'
minute: 60000

parse:
  nodes: 'dbservice1 dbservice2 logservice1 logservice2 mobservice1 mobservice2 redisservice1 redisservice2 webservice1 webservice2'
  parse_dir: 'parse'
  metric_path: 'data/gaia/test/anomalies/metrics.json'
  trace_path: 'data/gaia/test/anomalies/trace.json' 
  log_path: 'data/gaia/test/anomalies/stratification.npy' 
  save_path: 'data/gaia/test/parse/stratification_texts.pkl' 

fasttext:
  supervised: True
  dataset: 'gaia'
  nodes: 'dbservice1 dbservice2 logservice1 logservice2 mobservice1 mobservice2 redisservice1 redisservice2 webservice1 webservice2'
  text_path: 'data/gaia/test/parse/stratification_texts.pkl'
  fasttext_dir: 'data/gaia/test/fasttext'
  temp_dir: 'data/gaia/test/fasttext/temp'
  train_path: 'data/gaia/test/fasttext/temp/train.txt'
  test_path: 'data/gaia/test/fasttext/temp/test.txt'
  train_da_path: 'data/gaia/test/fasttext/temp/train_da.txt'
  save_path: 'data/gaia/test/fasttext/event_embedding.pkl'
  vector_dim: 100
  sample_count: 1000
  edit_count: 1
  da_method: 'w2v'
  minCount: 1
  epoch: 10

sentence_embedding:
  K_S: 10 
  train_path: 'data/gaia/test/fasttext/temp/train.txt'
  test_path: 'data/gaia/test/fasttext/temp/test.txt'
  source_path: 'data/gaia/test/fasttext/event_embedding.pkl'
  save_path: 'data/gaia/test/sentence_embedding.pkl'

he_dgl:
  nodes: 'dbservice1 dbservice2 logservice1 logservice2 mobservice1 mobservice2 redisservice1 redisservice2 webservice1 webservice2'
  dataset: 'gaia'
  heterogeneous: False 
  data_dir: ''
  save_dir: 'data/gaia/test/dgl/stratification_10'
  Xs: 'data/gaia/test/sentence_embedding.pkl'
  run_table: 'data/gaia/test/anomalies/labels_converted.csv' # 'demo_train160.csv'
  aug: False
  aug_size: 0
  N_S: 5
  N_A: 5
  TOPK_SA: 10
  save_model: False
  epoch: 6000 
  batch_size: 1000
  win_size: 10
  win_threshold: 0.0001
  lr: 0.001
  weight_decay: 0.0001
  seed: 2
  text_path: 'data/gaia/test/parse/stratification_texts.pkl'

source_data_path: 'data/gaia/source_data'
event_path: 'data/gaia/events'
feature_path: 'data/gaia/feature'
result_path: 'result/gaia/analysis'
exploration_path: 'exploration/gaia/pics'
trace_path: 'data/gaia/demo/trace'
log_path: 'data/gaia/demo/log'
metric_path: 'data/gaia/demo/metric'
feature_list:
  0: TFIDF_X
  1: BOW_X
  2: NGram_X
  3: TFIDF_BOW_NGram_X
  4: TFIDF_BOW_X
  5: TFIDF_NGram_X,
  6: BOW_NGram_X
feature: feature_list[0]